apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "your-chart.fullname" . }}-monitor
  labels:
    release: kube-prometheus-stack   # Match the Prometheus Operator stack name
    app: {{ include "your-chart.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "your-chart.name" . }}
  endpoints:
    - port: http   # The port where Application B exposes metrics
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
